const Cities = [
  { value: "rivne", label: "Rivne", country: "ukraine" },
  { value: "kyiv", label: "Kyiv", country: "ukraine" },
  { value: "new_york", label: "New York", country: "usa" },
  { value: "los_angeles", label: "Los Angeles", country: "usa" },
  { value: "toronto", label: "Toronto", country: "canada" },
  { value: "vancouver", label: "Vancouver", country: "canada" },
  { value: "berlin", label: "Berlin", country: "germany" },
  { value: "munich", label: "Munich", country: "germany" },
  { value: "paris", label: "Paris", country: "france" },
  { value: "lyon", label: "Lyon", country: "france" },
  { value: "rome", label: "Rome", country: "italy" },
  { value: "milan", label: "Milan", country: "italy" },
  { value: "madrid", label: "Madrid", country: "spain" },
  { value: "barcelona", label: "Barcelona", country: "spain" },
  { value: "tokyo", label: "Tokyo", country: "japan" },
  { value: "osaka", label: "Osaka", country: "japan" },
  { value: "beijing", label: "Beijing", country: "china" },
  { value: "shanghai", label: "Shanghai", country: "china" },
  { value: "mumbai", label: "Mumbai", country: "india" },
  { value: "delhi", label: "Delhi", country: "india" },
  { value: "sao_paulo", label: "Sao Paulo", country: "brazil" },
  { value: "rio_de_janeiro", label: "Rio de Janeiro", country: "brazil" },
  { value: "sydney", label: "Sydney", country: "australia" },
  { value: "melbourne", label: "Melbourne", country: "australia" },
  { value: "mexico_city", label: "Mexico City", country: "mexico" },
  { value: "guadalajara", label: "Guadalajara", country: "mexico" },
  { value: "moscow", label: "Moscow", country: "russia" },
  { value: "saint_petersburg", label: "Saint Petersburg", country: "russia" },
  { value: "seoul", label: "Seoul", country: "south_korea" },
  { value: "busan", label: "Busan", country: "south_korea" },
  { value: "johannesburg", label: "Johannesburg", country: "south_africa" },
  { value: "cape_town", label: "Cape Town", country: "south_africa" },
  { value: "buenos_aires", label: "Buenos Aires", country: "argentina" },
  { value: "cordoba", label: "Cordoba", country: "argentina" },
  { value: "lagos", label: "Lagos", country: "nigeria" },
  { value: "abuja", label: "Abuja", country: "nigeria" },
  { value: "cairo", label: "Cairo", country: "egypt" },
  { value: "alexandria", label: "Alexandria", country: "egypt" },
  { value: "stockholm", label: "Stockholm", country: "sweden" },
  { value: "gothenburg", label: "Gothenburg", country: "sweden" },
  { value: "oslo", label: "Oslo", country: "norway" },
  { value: "bergen", label: "Bergen", country: "norway" },
  { value: "copenhagen", label: "Copenhagen", country: "denmark" },
  { value: "aarhus", label: "Aarhus", country: "denmark" },
  { value: "helsinki", label: "Helsinki", country: "finland" },
  { value: "espoo", label: "Espoo", country: "finland" },
  { value: "amsterdam", label: "Amsterdam", country: "netherlands" },
  { value: "rotterdam", label: "Rotterdam", country: "netherlands" },
  { value: "brussels", label: "Brussels", country: "belgium" },
  { value: "antwerp", label: "Antwerp", country: "belgium" },
  { value: "zurich", label: "Zurich", country: "switzerland" },
  { value: "geneva", label: "Geneva", country: "switzerland" },
  { value: "vienna", label: "Vienna", country: "austria" },
  { value: "salzburg", label: "Salzburg", country: "austria" },
  { value: "warsaw", label: "Warsaw", country: "poland" },
  { value: "krakow", label: "Krakow", country: "poland" },
  { value: "lisbon", label: "Lisbon", country: "portugal" },
  { value: "porto", label: "Porto", country: "portugal" },
  { value: "athens", label: "Athens", country: "greece" },
  { value: "thessaloniki", label: "Thessaloniki", country: "greece" },
  { value: "istanbul", label: "Istanbul", country: "turkey" },
  { value: "ankara", label: "Ankara", country: "turkey" },
  { value: "riyadh", label: "Riyadh", country: "saudi_arabia" },
  { value: "jeddah", label: "Jeddah", country: "saudi_arabia" },
  { value: "tehran", label: "Tehran", country: "iran" },
  { value: "mashhad", label: "Mashhad", country: "iran" },
  { value: "jakarta", label: "Jakarta", country: "indonesia" },
  { value: "surabaya", label: "Surabaya", country: "indonesia" },
  { value: "bangkok", label: "Bangkok", country: "thailand" },
  { value: "chiang_mai", label: "Chiang Mai", country: "thailand" },
  { value: "kuala_lumpur", label: "Kuala Lumpur", country: "malaysia" },
  { value: "george_town", label: "George Town", country: "malaysia" },
  { value: "manila", label: "Manila", country: "philippines" },
  { value: "cebu", label: "Cebu", country: "philippines" },
  { value: "hanoi", label: "Hanoi", country: "vietnam" },
  { value: "ho_chi_minh_city", label: "Ho Chi Minh City", country: "vietnam" },
  { value: "karachi", label: "Karachi", country: "pakistan" },
  { value: "lahore", label: "Lahore", country: "pakistan" },
  { value: "dhaka", label: "Dhaka", country: "bangladesh" },
  { value: "chittagong", label: "Chittagong", country: "bangladesh" },
  { value: "bogota", label: "Bogota", country: "colombia" },
  { value: "medellin", label: "Medellin", country: "colombia" },
  { value: "santiago", label: "Santiago", country: "chile" },
  { value: "valparaiso", label: "Valparaiso", country: "chile" },
  { value: "lima", label: "Lima", country: "peru" },
  { value: "cusco", label: "Cusco", country: "peru" },
  { value: "caracas", label: "Caracas", country: "venezuela" },
  { value: "maracaibo", label: "Maracaibo", country: "venezuela" },
  { value: "auckland", label: "Auckland", country: "new_zealand" },
  { value: "wellington", label: "Wellington", country: "new_zealand" },
];

export default Cities;
