const Countries = [
    { value: "select", label: "Select" },
    { value: "ukraine", label: "Ukraine" },
    { value: "usa", label: "United States" },
    { value: "canada", label: "Canada" },
    { value: "germany", label: "Germany" },
    { value: "france", label: "France" },
    { value: "italy", label: "Italy" },
    { value: "spain", label: "Spain" },
    { value: "japan", label: "Japan" },
    { value: "china", label: "China" },
    { value: "india", label: "India" },
    { value: "brazil", label: "Brazil" },
    { value: "australia", label: "Australia" },
    { value: "mexico", label: "Mexico" },
    { value: "south_korea", label: "South Korea" },
    { value: "south_africa", label: "South Africa" },
    { value: "argentina", label: "Argentina" },
    { value: "nigeria", label: "Nigeria" },
    { value: "egypt", label: "Egypt" },
    { value: "sweden", label: "Sweden" },
    { value: "norway", label: "Norway" },
    { value: "denmark", label: "Denmark" },
    { value: "finland", label: "Finland" },
    { value: "netherlands", label: "Netherlands" },
    { value: "belgium", label: "Belgium" },
    { value: "switzerland", label: "Switzerland" },
    { value: "austria", label: "Austria" },
    { value: "poland", label: "Poland" },
    { value: "portugal", label: "Portugal" },
    { value: "greece", label: "Greece" },
    { value: "turkey", label: "Turkey" },
    { value: "saudi_arabia", label: "Saudi Arabia" },
    { value: "iran", label: "Iran" },
    { value: "indonesia", label: "Indonesia" },
    { value: "thailand", label: "Thailand" },
    { value: "malaysia", label: "Malaysia" },
    { value: "philippines", label: "Philippines" },
    { value: "vietnam", label: "Vietnam" },
    { value: "pakistan", label: "Pakistan" },
    { value: "bangladesh", label: "Bangladesh" },
    { value: "colombia", label: "Colombia" },
    { value: "chile", label: "Chile" },
    { value: "peru", label: "Peru" },
    { value: "venezuela", label: "Venezuela" },
    { value: "new_zealand", label: "New Zealand" },
];

export default Countries;
