import type { Metadata } from "next";
import UserSecure from "./user-secure/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserPageRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row items-center justify-center min-h-screen py-2">
        <UserSecure />
        {children}
    </div>
  );
}
